name: Build and Release DEB Package

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential

      - name: Install fpm
        run: sudo gem install fpm

      - name: Build DEB package
        run: |
          source .env && cp sys-update.sh sys-update && fpm -t deb -p sys-update_${VERSION}_amd64.deb

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: echo "$VERSION"
          release_name: echo "$VERSION"
          draft: false
          prerelease: false

      - name: Upload DEB Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: echo "./sys-update_${VERSION}_amd64.deb"
          asset_name: echo "sys-update_${VERSION]_amd64.deb"
          asset_content_type: application/x-debian-package
